### ISSUE TITLE
Array of folders, internet connection timeout and running as a service

### ISSUE THREAD

**Issue by marckean** [ScottHolden/IoPS#1]
Be great to allow for an array of folders containing .PS1 scripts, rather than just one folder.

Extension of the timeout, when the internet connection drops, it has retry logic to reconnect, but then after short period of time it just gives up, would be good to keep checking for internet so that when the internet does come back up again, it can be relied upon that IoPS will also come back online.

The latest version running as a service doesn't work, it only works if you run the .exe in the forground. 

Other than that, awesome work, great solution!

**Comment by marckean** [comment]
![Annotation 2019-05-22 174521](https://user-images.githubusercontent.com/7284874/58156693-0586ea80-7cba-11e9-9d06-c1719f7f8c39.jpg)

Here's a screenshot of the time out message when it eventually gives up trying to connect.

**Comment by ScottHolden** [comment]
I've put the initial run of fixes in #2 , I'll add a round of tests to them before the next release. I've yet to dig into the service issue.

**Comment by ScottHolden** [comment]
Merged, creating release now!

**Comment by ScottHolden** [comment]
Released: https://github.com/ScottHolden/IoPS/releases/tag/20190817.1

Let me know if you run into any issues.
